package main

// Represents a rail connection between two stations
type RailLink struct {
	fromStation string
	toStation   string
	line        string
	transitTime uint16
}

// Represents an on-foot interchange opportunity, either to a nearby station
// or to a different transit line from the same station
type Interchange struct {
	fromStation string
	fromLine    string
	toStation   string
	toLine      string
	transitTime uint16
}

// Return list of all rail links in the transit map
func GetRailLinks() []RailLink {
	return []RailLink{
		// BAKERLOO LINE
		{"Harrow & Wealdstone", "Kenton", "Bakerloo", 3},
		{"Kenton", "South Kenton", "Bakerloo", 2},
		{"South Kenton", "North Wembley", "Bakerloo", 2},
		{"North Wembley", "Wembley Central", "Bakerloo", 2},
		{"Wembley Central", "Stonebridge Park", "Bakerloo", 3},
		{"Stonebridge Park", "Harlesden", "Bakerloo", 2},
		{"Harlesden", "Willesden Junction", "Bakerloo", 2},
		{"Willesden Junction", "Kensal Green", "Bakerloo", 3},
		{"Kensal Green", "Queen's Park", "Bakerloo", 4},
		{"Queen's Park", "Kilburn Park", "Bakerloo", 1},
		{"Kilburn Park", "Maida Vale", "Bakerloo", 2},
		{"Maida Vale", "Warwick Avenue", "Bakerloo", 2},
		{"Warwick Avenue", "Paddington", "Bakerloo", 2},
		{"Paddington", "Edgware Road", "Bakerloo", 1},
		{"Edgware Road", "Marylebone", "Bakerloo", 2},
		{"Marylebone", "Baker Street", "Bakerloo", 1},
		{"Baker Street", "Regent's Park", "Bakerloo", 2},
		{"Regent's Park", "Oxford Circus", "Bakerloo", 2},
		{"Oxford Circus", "Piccadilly Circus", "Bakerloo", 2},
		{"Piccadilly Circus", "Charing Cross", "Bakerloo", 2},
		{"Charing Cross", "Embankment", "Bakerloo", 1},
		{"Embankment", "Waterloo", "Bakerloo", 2},
		{"Waterloo", "Lambeth North", "Bakerloo", 1},
		{"Lambeth North", "Elephant & Castle", "Bakerloo", 4},

		// CENTRAL LINE
		{"West Ruislip", "Ruislip Gardens", "Central", 3},
		{"Ruislip Gardens", "South Ruislip", "Central", 2},
		{"South Ruislip", "Northolt", "Central", 3},
		{"Northolt", "Greenford", "Central", 2},
		{"Greenford", "Perivale", "Central", 2},
		{"Perivale", "Hanger Lane", "Central", 2},
		{"Hanger Lane", "North Acton", "Central", 4},
		{"North Acton", "East Acton", "Central", 2},
		{"East Acton", "White City", "Central", 4},
		{"White City", "Shepherd's Bush", "Central", 3},
		{"Shepherd's Bush", "Holland Park", "Central", 1},
		{"Holland Park", "Notting Hill Gate", "Central", 2},
		{"Notting Hill Gate", "Queensway", "Central", 1},
		{"Queensway", "Lancaster Gate", "Central", 2},
		{"Lancaster Gate", "Marble Arch", "Central", 2},
		{"Marble Arch", "Bond Street", "Central", 2},
		{"Bond Street", "Oxford Circus", "Central", 1},
		{"Oxford Circus", "Tottenham Court Road", "Central", 1},
		{"Tottenham Court Road", "Holborn", "Central", 3},
		{"Holborn", "Chancery Lane", "Central", 1},
		{"Chancery Lane", "St. Paul's", "Central", 2},
		{"St. Paul's", "Bank", "Central", 2},
		{"Bank", "Liverpool Street", "Central", 2},
		{"Liverpool Street", "Bethnal Green (Central)", "Central", 3},
		{"Bethnal Green (Central)", "Mile End", "Central", 3},
		{"Mile End", "Stratford", "Central", 3},
		{"Stratford", "Leyton", "Central", 3},
		{"Leyton", "Leytonstone", "Central", 3},
		{"Leytonstone", "Wanstead", "Central", 3},
		{"Wanstead", "Redbridge", "Central", 2},
		{"Redbridge", "Gants Hill", "Central", 2},
		{"Gants Hill", "Newbury Park", "Central", 4},
		{"Newbury Park", "Barkingside", "Central", 1},
		{"Barkingside", "Fairlop", "Central", 2},
		{"Fairlop", "Hainault", "Central", 4},
		{"Hainault", "Grange Hill", "Central", 3},
		{"Grange Hill", "Chigwell", "Central", 2},
		{"Chigwell", "Roding Valley", "Central", 3},
		{"Roding Valley", "Woodford", "Central", 2},
		{"Ealing Broadway", "West Acton", "Central", 2},
		{"West Acton", "North Acton", "Central", 3},
		{"Leytonstone", "Snaresbrook", "Central", 2},
		{"Snaresbrook", "South Woodford", "Central", 2},
		{"South Woodford", "Woodford", "Central", 3},
		{"Woodford", "Buckhurst Hill", "Central", 2},
		{"Buckhurst Hill", "Loughton", "Central", 3},
		{"Loughton", "Debden", "Central", 3},
		{"Debden", "Theydon Bois", "Central", 3},
		{"Theydon Bois", "Epping", "Central", 3},

		// CIRCLE LINE
		{"Hammersmith", "Goldhawk Road", "Circle", 4},
		{"Goldhawk Road", "Shepherd's Bush Market", "Circle", 1},
		{"Shepherd's Bush Market", "Wood Lane", "Circle", 1},
		{"Wood Lane", "Latimer Road", "Circle", 2},
		{"Latimer Road", "Ladbroke Grove", "Circle", 1},
		{"Ladbroke Grove", "Westbourne Park", "Circle", 2},
		{"Westbourne Park", "Royal Oak", "Circle", 2},
		{"Royal Oak", "Paddington", "Circle", 2},
		{"Paddington", "Edgware Road", "Circle", 3},
		{"Edgware Road", "Baker Street", "Circle", 3},
		{"Baker Street", "Great Portland Street", "Circle", 2},
		{"Great Portland Street", "Euston Square", "Circle", 2},
		{"Euston Square", "King's Cross St. Pancras", "Circle", 2},
		{"King's Cross St. Pancras", "Farringdon", "Circle", 3},
		{"Farringdon", "Barbican", "Circle", 1},
		{"Barbican", "Moorgate", "Circle", 2},
		{"Moorgate", "Liverpool Street", "Circle", 2},
		{"Liverpool Street", "Aldgate", "Circle", 3},
		{"Aldgate", "Tower Hill", "Circle", 2},
		{"Tower Hill", "Monument", "Circle", 2},
		{"Monument", "Cannon Street", "Circle", 1},
		{"Cannon Street", "Mansion House", "Circle", 1},
		{"Mansion House", "Blackfriars", "Circle", 2},
		{"Blackfriars", "Temple", "Circle", 2},
		{"Temple", "Embankment", "Circle", 1},
		{"Embankment", "Westminster", "Circle", 2},
		{"Westminster", "St. James's Park", "Circle", 2},
		{"St. James's Park", "Victoria", "Circle", 1},
		{"Victoria", "Sloane Square", "Circle", 2},
		{"Sloane Square", "South Kensington", "Circle", 3},
		{"South Kensington", "Gloucester Road", "Circle", 4},
		{"Gloucester Road", "High Street Kensington", "Circle", 2},
		{"High Street Kensington", "Notting Hill Gate", "Circle", 2},
		{"Notting Hill Gate", "Bayswater", "Circle", 2},
		{"Bayswater", "Paddington", "Circle", 2},

		// DISTRICT LINE
		{"Ealing Broadway", "Ealing Common", "District", 4},
		{"Ealing Common", "Acton Town", "District", 4},
		{"Acton Town", "Chiswick Park", "District", 2},
		{"Chiswick Park", "Turnham Green", "District", 4},
		{"Turnham Green", "Stamford Park", "District", 1},
		{"Stamford Park", "Ravenscourt Park", "District", 2},
		{"Ravenscourt Park", "Hammersmith", "District", 2},
		{"Hammersmith", "Barons Court", "District", 2},
		{"Barons Court", "West Kensington", "District", 1},
		{"West Kensington", "Earl's Court", "District", 3},
		{"Earl's Court", "Gloucester Road", "District", 3},
		{"Gloucester Road", "South Kensington", "District", 1},
		{"South Kensington", "Sloane Square", "District", 3},
		{"Sloane Square", "Victoria", "District", 2},
		{"Victoria", "St. James's Park", "District", 1},
		{"St. James's Park", "Westminster", "District", 2},
		{"Westminster", "Embankment", "District", 2},
		{"Embankment", "Temple", "District", 1},
		{"Temple", "Blackfriars", "District", 2},
		{"Blackfriars", "Mansion House", "District", 2},
		{"Mansion House", "Cannon Street", "District", 1},
		{"Cannon Street", "Monument", "District", 1},
		{"Monument", "Tower Hill", "District", 2},
		{"Tower Hill", "Aldgate East", "District", 2},
		{"Aldgate East", "Whitechapel", "District", 3},
		{"Whitechapel", "Stepney Green", "District", 2},
		{"Stepney Green", "Mile End", "District", 2},
		{"Mile End", "Bow Road", "District", 1},
		{"Bow Road", "Bromley-by-Bow", "District", 2},
		{"Bromley-by-Bow", "West Ham", "District", 3},
		{"West Ham", "Plaistow", "District", 2},
		{"Plaistow", "Upton Park", "District", 2},
		{"Upton Park", "East Ham", "District", 2},
		{"East Ham", "Barking", "District", 4},
		{"Barking", "Upney", "District", 2},
		{"Upney", "Becontree", "District", 2},
		{"Becontree", "Dagenham Heathway", "District", 2},
		{"Dagenham Heathway", "Dagenham East", "District", 3},
		{"Dagenham East", "Elm Park", "District", 3},
		{"Elm Park", "Hornchurch", "District", 2},
		{"Hornchurch", "Upminster Bridge", "District", 2},
		{"Upminster Bridge", "Upminster", "District", 2},
		{"Richmond", "Kew Gardens", "District", 4},
		{"Kew Gardens", "Gunnersbury", "District", 3},
		{"Gunnersbury", "Turnham Green", "District", 5},
		{"Wimbledon", "Wimbledon Park", "District", 3},
		{"Wimbledon Park", "Southfields", "District", 3},
		{"Southfields", "East Putney", "District", 2},
		{"East Putney", "Putney Bridge", "District", 3},
		{"Putney Bridge", "Parsons Green", "District", 2},
		{"Parsons Green", "Fulham Broadway", "District", 1},
		{"Fulham Broadway", "West Brompton", "District", 2},
		{"West Brompton", "Earl's Court", "District", 3},
		{"Earl's Court", "High Street Kensington", "District", 3},
		{"High Street Kensington", "Notting Hill Gate", "District", 2},
		{"Notting Hill Gate", "Bayswater", "District", 1},
		{"Bayswater", "Paddington", "District", 3},
		{"Paddington", "Edgware Road", "District", 2},

		// DOCKLANDS LIGHT RAILWAY LINE
		{"Stratford International", "Stratford", "Docklands Light Railway", 2},
		{"Stratford", "Stratford High Street", "Docklands Light Railway", 1},
		{"Stratford High Street", "Abbey Road", "Docklands Light Railway", 2},
		{"Abbey Road", "West Ham", "Docklands Light Railway", 2},
		{"West Ham", "Star Lane", "Docklands Light Railway", 2},
		{"Star Lane", "Canning Town", "Docklands Light Railway", 2},
		{"Canning Town", "West Silvertown", "Docklands Light Railway", 3},
		{"West Silvertown", "Pontoon Dock", "Docklands Light Railway", 1},
		{"Pontoon Dock", "London City Airport", "Docklands Light Railway", 2},
		{"London City Airport", "King George V", "Docklands Light Railway", 2},
		{"King George V", "Woolwich Arsenal", "Docklands Light Railway", 4},
		{"Lewisham", "Elverson Road", "Docklands Light Railway", 2},
		{"Elverson Road", "Deptford Bridge", "Docklands Light Railway", 1},
		{"Deptford Bridge", "Greenwich", "Docklands Light Railway", 2},
		{"Greenwich", "Cutty Sark for Maritime Greenwich", "Docklands Light Railway", 2},
		{"Cutty Sark for Maritime Greenwich", "Island Gardens", "Docklands Light Railway", 1},
		{"Island Gardens", "Mudchute", "Docklands Light Railway", 2},
		{"Mudchute", "Crossharbour", "Docklands Light Railway", 1},
		{"Crossharbour", "South Quay", "Docklands Light Railway", 2},
		{"South Quay", "Heron Quays", "Docklands Light Railway", 1},
		{"Heron Quays", "Canary Wharf", "Docklands Light Railway", 2},
		{"Canary Wharf", "West India Quay", "Docklands Light Railway", 1},
		{"West India Quay", "Westferry", "Docklands Light Railway", 2},
		{"Westferry", "Limehouse", "Docklands Light Railway", 2},
		{"Limehouse", "Shadwell", "Docklands Light Railway", 2},
		{"Shadwell", "Bank", "Docklands Light Railway", 3},
		{"Poplar", "Blackwall", "Docklands Light Railway", 3},
		{"Blackwall", "East India", "Docklands Light Railway", 3},
		{"East India", "Canning Town", "Docklands Light Railway", 3},
		{"Canning Town", "Royal Victoria", "Docklands Light Railway", 3},
		{"Royal Victoria", "Custom House for ExCeL", "Docklands Light Railway", 3},
		{"Custom House for ExCeL", "Prince Regent", "Docklands Light Railway", 3},
		{"Prince Regent", "Royal Albert", "Docklands Light Railway", 3},
		{"Royal Albert", "Beckton Park", "Docklands Light Railway", 3},
		{"Beckton Park", "Cyprus", "Docklands Light Railway", 3},
		{"Cyprus", "Gallions Reach", "Docklands Light Railway", 3},
		{"Gallions Reach", "Beckton", "Docklands Light Railway", 3},
		{"Stratford", "Pudding Mill Lane", "Docklands Light Railway", 2},
		{"Pudding Mill Lane", "Bow Church", "Docklands Light Railway", 2},
		{"Bow Church", "Devons Road", "Docklands Light Railway", 2},
		{"Devons Road", "Langdon Park", "Docklands Light Railway", 1},
		{"Langdon Park", "All Saints", "Docklands Light Railway", 2},
		{"All Saints", "Poplar", "Docklands Light Railway", 1},
		{"Tower Gateway", "Shadwell", "Docklands Light Railway", 2},

		// ELIZABETH LINE
		{"Reading", "Twyford", "Elizabeth", 5},
		{"Twyford", "Maidenhead", "Elizabeth", 7},
		{"Maidenhead", "Taplow", "Elizabeth", 3},
		{"Taplow", "Burnham", "Elizabeth", 4},
		{"Burnham", "Slough", "Elizabeth", 3},
		{"Slough", "Langley", "Elizabeth", 4},
		{"Langley", "Iver", "Elizabeth", 2},
		{"Iver", "West Drayton", "Elizabeth", 3},
		{"West Drayton", "Hayes & Harlington", "Elizabeth", 3},
		{"Heathrow Terminal 5", "Heathrow Terminals 2 & 3", "Elizabeth", 4},
		{"Heathrow Terminals 4", "Heathrow Terminals 2 & 3", "Elizabeth", 4},
		{"Heathrow Terminals 2 & 3", "Hayes & Harlington", "Elizabeth", 5},
		{"Hayes & Harlington", "Southall", "Elizabeth", 3},
		{"Southall", "Hanwell", "Elizabeth", 3},
		{"Hanwell", "West Ealing", "Elizabeth", 3},
		{"West Ealing", "Ealing Broadway", "Elizabeth", 3},
		{"Ealing Broadway", "Acton Main Line", "Elizabeth", 3},
		{"Acton Main Line", "Paddington", "Elizabeth", 3},
		{"Paddington", "Bond Street", "Elizabeth", 3},
		{"Bond Street", "Tottenham Court Road", "Elizabeth", 3},
		{"Tottenham Court Road", "Farringdon", "Elizabeth", 3},
		{"Farringdon", "Liverpool Street", "Elizabeth", 3},
		{"Liverpool Street", "Whitechapel", "Elizabeth", 3},
		{"Whitechapel", "Canary Wharf", "Elizabeth", 3},
		{"Canary Wharf", "Custom House for ExCeL", "Elizabeth", 4},
		{"Custom House for ExCeL", "Woolwich", "Elizabeth", 4},
		{"Woolwich", "Abbey Wood", "Elizabeth", 5},
		{"Whitechapel", "Stratford", "Elizabeth", 6},
		{"Stratford", "Maryland", "Elizabeth", 2},
		{"Maryland", "Forest Gate", "Elizabeth", 2},
		{"Forest Gate", "Manor Park", "Elizabeth", 2},
		{"Manor Park", "Ilford", "Elizabeth", 3},
		{"Ilford", "Seven Kings", "Elizabeth", 3},
		{"Seven Kings", "Goodmayes", "Elizabeth", 2},
		{"Goodmayes", "Chadwell Heath", "Elizabeth", 2},
		{"Chadwell Heath", "Romford", "Elizabeth", 4},
		{"Romford", "Gidea Park", "Elizabeth", 3},
		{"Gidea Park", "Harold Wood", "Elizabeth", 3},
		{"Harold Wood", "Brentwood", "Elizabeth", 4},
		{"Brentwood", "Shenfield", "Elizabeth", 6},

		// HAMMERSMITH & CITY LINE
		{"Hammersmith", "Goldhawk Road", "Hammersmith & City", 4},
		{"Goldhawk Road", "Shepherd's Bush Market", "Hammersmith & City", 1},
		{"Shepherd's Bush Market", "Wood Lane", "Hammersmith & City", 1},
		{"Wood Lane", "Latimer Road", "Hammersmith & City", 2},
		{"Latimer Road", "Ladbroke Grove", "Hammersmith & City", 1},
		{"Ladbroke Grove", "Westbourne Park", "Hammersmith & City", 2},
		{"Westbourne Park", "Royal Oak", "Hammersmith & City", 2},
		{"Royal Oak", "Paddington", "Hammersmith & City", 2},
		{"Paddington", "Edgware Road", "Hammersmith & City", 3},
		{"Edgware Road", "Baker Street", "Hammersmith & City", 3},
		{"Baker Street", "Great Portland Street", "Hammersmith & City", 2},
		{"Great Portland Street", "Euston Square", "Hammersmith & City", 2},
		{"Euston Square", "King's Cross St. Pancras", "Hammersmith & City", 2},
		{"King's Cross St. Pancras", "Farringdon", "Hammersmith & City", 3},
		{"Farringdon", "Barbican", "Hammersmith & City", 1},
		{"Barbican", "Moorgate", "Hammersmith & City", 2},
		{"Moorgate", "Liverpool Street", "Hammersmith & City", 2},
		{"Liverpool Street", "Aldgate East", "Hammersmith & City", 6},
		{"Aldgate East", "Whitechapel", "Hammersmith & City", 2},
		{"Whitechapel", "Stepney Green", "Hammersmith & City", 2},
		{"Stepney Green", "Mile End", "Hammersmith & City", 2},
		{"Mile End", "Bow Road", "Hammersmith & City", 2},
		{"Bow Road", "Bromley-by-Bow", "Hammersmith & City", 2},
		{"Bromley-by-Bow", "West Ham", "Hammersmith & City", 3},
		{"West Ham", "Plaistow", "Hammersmith & City", 2},
		{"Plaistow", "Upton Park", "Hammersmith & City", 2},
		{"Upton Park", "East Ham", "Hammersmith & City", 2},
		{"East Ham", "Barking", "Hammersmith & City", 4},

		// JUBILEE LINE
		{"Stanmore", "Canons Park", "Jubilee", 4},
		{"Canons Park", "Queensbury", "Jubilee", 3},
		{"Queensbury", "Kingsbury", "Jubilee", 2},
		{"Kingsbury", "Wembley Park", "Jubilee", 4},
		{"Wembley Park", "Neasden", "Jubilee", 3},
		{"Neasden", "Dollis Hill", "Jubilee", 2},
		{"Dollis Hill", "Willesden Green", "Jubilee", 2},
		{"Willesden Green", "Kilburn", "Jubilee", 2},
		{"Kilburn", "West Hampstead", "Jubilee", 2},
		{"West Hampstead", "Finchley Road", "Jubilee", 1},
		{"Finchley Road", "Swiss Cottage", "Jubilee", 2},
		{"Swiss Cottage", "St. John's Wood", "Jubilee", 1},
		{"St. John's Wood", "Baker Street", "Jubilee", 3},
		{"Baker Street", "Bond Street", "Jubilee", 2},
		{"Bond Street", "Green Park", "Jubilee", 2},
		{"Green Park", "Westminster", "Jubilee", 2},
		{"Westminster", "Waterloo", "Jubilee", 2},
		{"Waterloo", "Southwark", "Jubilee", 1},
		{"Southwark", "London Bridge", "Jubilee", 2},
		{"London Bridge", "Bermondsey", "Jubilee", 2},
		{"Bermondsey", "Canada Water", "Jubilee", 2},
		{"Canada Water", "Canary Wharf", "Jubilee", 2},
		{"Canary Wharf", "North Greenwich", "Jubilee", 3},
		{"North Greenwich", "Canning Town", "Jubilee", 2},
		{"Canning Town", "West Ham", "Jubilee", 3},
		{"West Ham", "Stratford", "Jubilee", 3},

		// METROPOLITAN LINE
		{"Uxbridge", "Hillingdon", "Metropolitan", 3},
		{"Hillingdon", "Ickenham", "Metropolitan", 2},
		{"Ickenham", "Ruislip", "Metropolitan", 3},
		{"Ruislip", "Ruislip Manor", "Metropolitan", 1},
		{"Ruislip Manor", "Eastcote", "Metropolitan", 2},
		{"Eastcote", "Rayners Lane", "Metropolitan", 4},
		{"Rayners Lane", "West Harrow", "Metropolitan", 2},
		{"West Harrow", "Harrow-on-the-Hill", "Metropolitan", 2},
		{"Harrow-on-the-Hill", "Northwick Park", "Metropolitan", 3},
		{"Northwick Park", "Preston Road", "Metropolitan", 2},
		{"Preston Road", "Wembley Park", "Metropolitan", 3},
		{"Wembley Park", "Finchley Road", "Metropolitan", 7},
		{"Finchley Road", "Baker Street", "Metropolitan", 6},
		{"Baker Street", "Great Portland Street", "Metropolitan", 2},
		{"Great Portland Street", "Euston Square", "Metropolitan", 2},
		{"Euston Square", "King's Cross St. Pancras", "Metropolitan", 2},
		{"King's Cross St. Pancras", "Farringdon", "Metropolitan", 3},
		{"Farringdon", "Barbican", "Metropolitan", 1},
		{"Barbican", "Moorgate", "Metropolitan", 2},
		{"Moorgate", "Liverpool Street", "Metropolitan", 2},
		{"Liverpool Street", "Aldgate", "Metropolitan", 3},
		{"Amersham", "Chalfont & Latimer", "Metropolitan", 4},
		{"Chalfont & Latimer", "Chorleywood", "Metropolitan", 4},
		{"Chorleywood", "Rickmansworth", "Metropolitan", 4},
		{"Rickmansworth", "Moor Park", "Metropolitan", 4},
		{"Moor Park", "Northwood", "Metropolitan", 3},
		{"Northwood", "Northwood Hills", "Metropolitan", 2},
		{"Northwood Hills", "Pinner", "Metropolitan", 3},
		{"Pinner", "North Harrow", "Metropolitan", 2},
		{"North Harrow", "Harrow-on-the-Hill", "Metropolitan", 3},
		{"Chesham", "Chalfont & Latimer", "Metropolitan", 8},
		{"Watford", "Croxley", "Metropolitan", 4},
		{"Croxley", "Moor Park", "Metropolitan", 4},

		// NORTHERN LINE
		{"Morden", "South Wimbledon", "Northern", 3},
		{"South Wimbledon", "Colliers Wood", "Northern", 2},
		{"Colliers Wood", "Tooting Broadway", "Northern", 2},
		{"Tooting Broadway", "Tooting Bec", "Northern", 2},
		{"Tooting Bec", "Balham", "Northern", 1},
		{"Balham", "Clapham South", "Northern", 2},
		{"Clapham South", "Clapham Common", "Northern", 2},
		{"Clapham Common", "Clapham North", "Northern", 2},
		{"Clapham North", "Stockwell", "Northern", 1},
		{"Stockwell", "Oval", "Northern", 2},
		{"Oval", "Kennington", "Northern", 3},
		{"Kennington", "Elephant & Castle", "Northern", 2},
		{"Elephant & Castle", "Borough", "Northern", 2},
		{"Borough", "London Bridge", "Northern", 1},
		{"London Bridge", "Bank", "Northern", 2},
		{"Bank", "Moorgate", "Northern", 2},
		{"Moorgate", "Old Street", "Northern", 2},
		{"Old Street", "Angel", "Northern", 2},
		{"Angel", "King's Cross St. Pancras", "Northern", 2},
		{"King's Cross St. Pancras", "Euston", "Northern", 2},
		{"Euston", "Camden Town", "Northern", 4},
		{"Camden Town", "Kentish Town", "Northern", 2},
		{"Kentish Town", "Tufnell Park", "Northern", 1},
		{"Tufnell Park", "Archway", "Northern", 2},
		{"Archway", "Highgate", "Northern", 2},
		{"Highgate", "East Finchley", "Northern", 3},
		{"East Finchley", "Finchley Central", "Northern", 4},
		{"Finchley Central", "West Finchley", "Northern", 3},
		{"West Finchley", "Woodside Park", "Northern", 1},
		{"Woodside Park", "Totteridge & Whetstone", "Northern", 3},
		{"Totteridge & Whetstone", "High Barnet", "Northern", 3},
		{"Finchley Central", "Mill Hill East", "Northern", 2},
		{"Battersea Power Station", "Nine Elms", "Northern", 3},
		{"Nine Elms", "Kennington", "Northern", 3},
		{"Kennington", "Waterloo", "Northern", 2},
		{"Waterloo", "Embankment", "Northern", 2},
		{"Embankment", "Charing Cross", "Northern", 1},
		{"Charing Cross", "Leicester Square", "Northern", 1},
		{"Leicester Square", "Tottenham Court Road", "Northern", 1},
		{"Tottenham Court Road", "Goodge Street", "Northern", 2},
		{"Goodge Street", "Warren Street", "Northern", 1},
		{"Warren Street", "Euston", "Northern", 2},
		{"Euston", "Mornington Crescent", "Northern", 2},
		{"Mornington Crescent", "Camden Town", "Northern", 2},
		{"Camden Town", "Chalk Farm", "Northern", 2},
		{"Chalk Farm", "Belsize Park", "Northern", 2},
		{"Belsize Park", "Hampstead", "Northern", 2},
		{"Hampstead", "Golders Green", "Northern", 3},
		{"Golders Green", "Brent Cross", "Northern", 2},
		{"Brent Cross", "Hendon Central", "Northern", 2},
		{"Hendon Central", "Colindale", "Northern", 3},
		{"Colindale", "Burnt Oak", "Northern", 2},
		{"Burnt Oak", "Edgware", "Northern", 2},

		// OVERGROUND LINE
		{"Watford Junction", "Watford High Street", "Overground", 3},
		{"Watford High Street", "Bushey", "Overground", 2},
		{"Bushey", "Carpenders Park", "Overground", 3},
		{"Carpenders Park", "Hatch End", "Overground", 3},
		{"Hatch End", "Headstone Lane", "Overground", 2},
		{"Headstone Lane", "Harrow & Wealdstone", "Overground", 3},
		{"Harrow & Wealdstone", "Kenton", "Overground", 4},
		{"Kenton", "South Kenton", "Overground", 2},
		{"South Kenton", "North Wembley", "Overground", 2},
		{"North Wembley", "Wembley Central", "Overground", 2},
		{"Wembley Central", "Stonebridge Park", "Overground", 3},
		{"Stonebridge Park", "Harlesden", "Overground", 2},
		{"Harlesden", "Willesden Junction", "Overground", 3},
		{"Willesden Junction", "Kensal Green", "Overground", 2},
		{"Kensal Green", "Queen's Park", "Overground", 3},
		{"Queen's Park", "Kilburn High Road", "Overground", 2},
		{"Kilburn High Road", "South Hampstead", "Overground", 2},
		{"South Hampstead", "Euston", "Overground", 9},
		{"Gospel Oak", "Upper Holloway", "Overground", 4},
		{"Upper Holloway", "Crouch Hill", "Overground", 2},
		{"Crouch Hill", "Harringay Green Lanes", "Overground", 3},
		{"Harringay Green Lanes", "South Tottenham", "Overground", 4},
		{"South Tottenham", "Blackhorse Road", "Overground", 3},
		{"Blackhorse Road", "Walthamstow Queen's Road", "Overground", 2},
		{"Walthamstow Queen's Road", "Leyton Midland Road", "Overground", 3},
		{"Leyton Midland Road", "Leytonstone High Road", "Overground", 2},
		{"Leytonstone High Road", "Wanstead Park", "Overground", 3},
		{"Wanstead Park", "Woodgrange Park", "Overground", 3},
		{"Woodgrange Park", "Barking", "Overground", 5},
		{"Barking", "Barking Riverside", "Overground", 7},
		{"Romford", "Emerson Park", "Overground", 5},
		{"Emerson Park", "Upminster", "Overground", 4},
		{"Clapham Junction", "Imperial Wharf", "Overground", 4},
		{"Imperial Wharf", "West Brompton", "Overground", 3},
		{"West Brompton", "Kensington (Olympia)", "Overground", 3},
		{"Kensington (Olympia)", "Shepherd's Bush", "Overground", 3},
		{"Shepherd's Bush", "Willesden Junction", "Overground", 7},
		{"Richmond", "Kew Gardens", "Overground", 3},
		{"Kew Gardens", "Gunnersbury", "Overground", 3},
		{"Gunnersbury", "South Acton", "Overground", 3},
		{"South Acton", "Acton Central", "Overground", 3},
		{"Acton Central", "Willesden Junction", "Overground", 5},
		{"Willesden Junction", "Kensal Rise", "Overground", 3},
		{"Kensal Rise", "Brondesbury Park", "Overground", 2},
		{"Brondesbury Park", "Brondesbury", "Overground", 1},
		{"Brondesbury", "West Hampstead", "Overground", 2},
		{"West Hampstead", "Finchley Road & Frognal", "Overground", 2},
		{"Finchley Road & Frognal", "Hampstead Heath", "Overground", 2},
		{"Hampstead Heath", "Gospel Oak", "Overground", 3},
		{"Gospel Oak", "Kentish Town West", "Overground", 2},
		{"Kentish Town West", "Camden Road", "Overground", 3},
		{"Camden Road", "Caledonian Road & Barnsbury", "Overground", 3},
		{"Caledonian Road & Barnsbury", "Highbury & Islington", "Overground", 3},
		{"Highbury & Islington", "Canonbury", "Overground", 2},
		{"Canonbury", "Dalston Kingsland", "Overground", 3},
		{"Dalston Kingsland", "Hackney Central", "Overground", 2},
		{"Hackney Central", "Homerton", "Overground", 3},
		{"Homerton", "Hackney Wick", "Overground", 2},
		{"Hackney Wick", "Stratford", "Overground", 6},
		{"Liverpool Street", "Bethnal Green (Overground)", "Overground", 3},
		{"Bethnal Green (Overground)", "Cambridge Heath", "Overground", 2},
		{"Cambridge Heath", "London Fields", "Overground", 2},
		{"London Fields", "Hackney Downs", "Overground", 2},
		{"Bethnal Green (Overground)", "Hackney Downs", "Overground", 4},
		{"Hackney Downs", "Clapton", "Overground", 3},
		{"Clapton", "St. James Street", "Overground", 3},
		{"St. James Street", "Walthamstow Central", "Overground", 2},
		{"Walthamstow Central", "Wood Street", "Overground", 3},
		{"Wood Street", "Highams Park", "Overground", 3},
		{"Highams Park", "Chingford", "Overground", 6},
		{"Hackney Downs", "Rectory Road", "Overground", 3},
		{"Rectory Road", "Stoke Newington", "Overground", 1},
		{"Stoke Newington", "Stamford Hill", "Overground", 2},
		{"Stamford Hill", "Seven Sisters", "Overground", 3},
		{"Seven Sisters", "Bruce Grove", "Overground", 2},
		{"Bruce Grove", "White Hart Lane", "Overground", 2},
		{"White Hart Lane", "Silver Street", "Overground", 2},
		{"Silver Street", "Edmonton Green", "Overground", 2},
		{"Edmonton Green", "Bush Hill Park", "Overground", 2},
		{"Bush Hill Park", "Enfield Town", "Overground", 5},
		{"Edmonton Green", "Southbury", "Overground", 3},
		{"Southbury", "Turkey Street", "Overground", 3},
		{"Turkey Street", "Theobalds Grove", "Overground", 2},
		{"Theobalds Grove", "Cheshunt", "Overground", 5},
		{"Highbury & Islington", "Canonbury", "Overground", 2},
		{"Canonbury", "Dalston Junction", "Overground", 3},
		{"Dalston Junction", "Haggerston", "Overground", 2},
		{"Haggerston", "Hoxton", "Overground", 2},
		{"Hoxton", "Shoreditch High Street", "Overground", 3},
		{"Shoreditch High Street", "Whitechapel", "Overground", 2},
		{"Whitechapel", "Shadwell", "Overground", 2},
		{"Shadwell", "Wapping", "Overground", 2},
		{"Wapping", "Rotherhithe", "Overground", 2},
		{"Rotherhithe", "Canada Water", "Overground", 2},
		{"Canada Water", "Surrey Quays", "Overground", 2},
		{"Surrey Quays", "New Cross", "Overground", 4},
		{"Surrey Quays", "Queens Road Peckham", "Overground", 7},
		{"Queens Road Peckham", "Peckham Rye", "Overground", 4},
		{"Peckham Rye", "Denmark Hill", "Overground", 4},
		{"Denmark Hill", "Clapham High Street", "Overground", 4},
		{"Clapham High Street", "Wandsworth Road", "Overground", 2},
		{"Wandsworth Road", "Clapham Junction", "Overground", 8},
		{"Surrey Quays", "New Cross Gate", "Overground", 5},
		{"New Cross Gate", "Brockley", "Overground", 3},
		{"Brockley", "Honor Oak Park", "Overground", 2},
		{"Honor Oak Park", "Forest Hill", "Overground", 3},
		{"Forest Hill", "Sydenham", "Overground", 3},
		{"Sydenham", "Crystal Palace", "Overground", 5},
		{"Sydenham", "Penge West", "Overground", 2},
		{"Penge West", "Anerley", "Overground", 2},
		{"Anerley", "Norwood Junction", "Overground", 3},
		{"Norwood Junction", "West Croydon", "Overground", 10},

		// PICCADILLY LINE
		{"Uxbridge", "Hillingdon", "Piccadilly", 3},
		{"Hillingdon", "Ickenham", "Piccadilly", 2},
		{"Ickenham", "Ruislip", "Piccadilly", 3},
		{"Ruislip", "Ruislip Manor", "Piccadilly", 1},
		{"Ruislip Manor", "Eastcote", "Piccadilly", 2},
		{"Eastcote", "Rayners Lane", "Piccadilly", 4},
		{"Rayners Lane", "South Harrow", "Piccadilly", 3},
		{"South Harrow", "Sudbury Hill", "Piccadilly", 2},
		{"Sudbury Hill", "Sudbury Town", "Piccadilly", 2},
		{"Sudbury Town", "Alperton", "Piccadilly", 3},
		{"Alperton", "Park Royal", "Piccadilly", 3},
		{"Park Royal", "North Ealing", "Piccadilly", 3},
		{"North Ealing", "Ealing Common", "Piccadilly", 2},
		{"Ealing Common", "Acton Town", "Piccadilly", 2},
		{"Acton Town", "Turnham Green", "Piccadilly", 3},
		{"Turnham Green", "Hammersmith", "Piccadilly", 3},
		{"Hammersmith", "Barons Court", "Piccadilly", 2},
		{"Barons Court", "Earl's Court", "Piccadilly", 3},
		{"Earl's Court", "Gloucester Road", "Piccadilly", 2},
		{"Gloucester Road", "South Kensington", "Piccadilly", 1},
		{"South Kensington", "Knightsbridge", "Piccadilly", 3},
		{"Knightsbridge", "Hyde Park Corner", "Piccadilly", 2},
		{"Hyde Park Corner", "Green Park", "Piccadilly", 2},
		{"Green Park", "Piccadilly Circus", "Piccadilly", 2},
		{"Piccadilly Circus", "Leicester Square", "Piccadilly", 1},
		{"Leicester Square", "Covent Garden", "Piccadilly", 1},
		{"Covent Garden", "Holborn", "Piccadilly", 2},
		{"Holborn", "Russell Square", "Piccadilly", 2},
		{"Russell Square", "King's Cross St. Pancras", "Piccadilly", 2},
		{"King's Cross St. Pancras", "Caledonian Road", "Piccadilly", 3},
		{"Caledonian Road", "Holloway Road", "Piccadilly", 3},
		{"Holloway Road", "Arsenal", "Piccadilly", 1},
		{"Arsenal", "Finsbury Park", "Piccadilly", 2},
		{"Finsbury Park", "Manor House", "Piccadilly", 2},
		{"Manor House", "Turnpike Lane", "Piccadilly", 3},
		{"Turnpike Lane", "Wood Green", "Piccadilly", 2},
		{"Wood Green", "Bounds Green", "Piccadilly", 3},
		{"Bounds Green", "Arnos Grove", "Piccadilly", 4},
		{"Arnos Grove", "Southgate", "Piccadilly", 2},
		{"Southgate", "Oakwood", "Piccadilly", 3},
		{"Oakwood", "Cockfosters", "Piccadilly", 3},
		{"Heathrow Terminal 5", "Heathrow Terminals 2 & 3", "Piccadilly", 4},
		{"Heathrow Terminals 2 & 3", "Hatton Cross", "Piccadilly", 3},
		{"Hatton Cross", "Heathrow Terminal 4", "Piccadilly", 4},
		{"Heathrow Terminal 4", "Heathrow Terminals 2 & 3", "Piccadilly", 6},
		{"Hatton Cross", "Hounslow West", "Piccadilly", 4},
		{"Hounslow West", "Hounslow Central", "Piccadilly", 2},
		{"Hounslow Central", "Hounslow East", "Piccadilly", 2},
		{"Hounslow East", "Osterley", "Piccadilly", 2},
		{"Osterley", "Boston Manor", "Piccadilly", 3},
		{"Boston Manor", "Northfields", "Piccadilly", 3},
		{"Northfields", "South Ealing", "Piccadilly", 1},
		{"South Ealing", "Acton Town", "Piccadilly", 4},

		// TRAMLINK LINE
		{"Wimbledon", "Dundonald Road", "Tramlink", 1},
		{"Dundonald Road", "Merton Park", "Tramlink", 2},
		{"Merton Park", "Morden Road", "Tramlink", 1},
		{"Morden Road", "Phipps Bridge", "Tramlink", 2},
		{"Phipps Bridge", "Belgrave Walk", "Tramlink", 1},
		{"Belgrave Walk", "Mitcham", "Tramlink", 2},
		{"Mitcham", "Mitcham Junction", "Tramlink", 3},
		{"Mitcham Junction", "Beddington Lane", "Tramlink", 2},
		{"Beddington Lane", "Therapia Lane", "Tramlink", 2},
		{"Therapia Lane", "Ampere Way", "Tramlink", 1},
		{"Ampere Way", "Waddon Marsh", "Tramlink", 2},
		{"Waddon Marsh", "Wandle Park", "Tramlink", 1},
		{"Wandle Park", "Reeves Corner", "Tramlink", 2},
		{"Reeves Corner", "Centrale", "Tramlink", 2},
		{"Centrale", "West Croydon", "Tramlink", 2},
		{"West Croydon", "Wellesley Road", "Tramlink", 3},
		{"Wellesley Road", "East Croydon", "Tramlink", 2},
		{"East Croydon", "Lebanon Road", "Tramlink", 2},
		{"Lebanon Road", "Sandilands", "Tramlink", 2},
		{"Sandilands", "Addiscombe", "Tramlink", 3},
		{"Addiscombe", "Blackhorse Lane", "Tramlink", 1},
		{"Blackhorse Lane", "Woodside", "Tramlink", 1},
		{"Woodside", "Arena", "Tramlink", 2},
		{"Arena", "Harrington Road", "Tramlink", 2},
		{"Harrington Road", "Birkbeck", "Tramlink", 3},
		{"Birkbeck", "Avenue Road", "Tramlink", 1},
		{"Avenue Road", "Beckenham Road", "Tramlink", 1},
		{"Beckenham Road", "Beckenham Junction", "Tramlink", 3},
		{"Elmers End", "Arena", "Tramlink", 2},
		{"New Addington", "King Henry's Drive", "Tramlink", 1},
		{"King Henry's Drive", "Fieldway", "Tramlink", 2},
		{"Fieldway", "Addington Village", "Tramlink", 2},
		{"Addington Village", "Gravel Hill", "Tramlink", 2},
		{"Gravel Hill", "Coombe Lane", "Tramlink", 3},
		{"Coombe Lane", "Lloyd Park", "Tramlink", 3},
		{"Lloyd Park", "Sandilands", "Tramlink", 4},
		{"East Croydon", "George Street", "Tramlink", 2},
		{"George Street", "Church Street", "Tramlink", 1},
		{"Church Street", "Centrale", "Tramlink", 1},

		// VICTORIA LINE
		{"Brixton", "Stockwell", "Victoria", 3},
		{"Stockwell", "Vauxhall", "Victoria", 2},
		{"Vauxhall", "Pimlico", "Victoria", 1},
		{"Pimlico", "Victoria", "Victoria", 2},
		{"Victoria", "Green Park", "Victoria", 2},
		{"Green Park", "Oxford Circus", "Victoria", 2},
		{"Oxford Circus", "Warren Street", "Victoria", 2},
		{"Warren Street", "Euston", "Victoria", 1},
		{"Euston", "King's Cross St. Pancras", "Victoria", 2},
		{"King's Cross St. Pancras", "Highbury & Islington", "Victoria", 3},
		{"Highbury & Islington", "Finsbury Park", "Victoria", 2},
		{"Finsbury Park", "Seven Sisters", "Victoria", 2},
		{"Seven Sisters", "Tottenham Hale", "Victoria", 2},
		{"Tottenham Hale", "Blackhorse Road", "Victoria", 2},
		{"Blackhorse Road", "Walthamstow Central", "Victoria", 1},

		// WATERLOO & CITY LINE
		{"Waterloo", "Bank", "Waterloo & City", 5},
	}
}

// Return list of all interchanges in the transit map
func GetInterchanges() []Interchange {
	return []Interchange{
		// INTERCHANGES FROM BAKERLOO LINE
		{"Baker Street", "Bakerloo", "Baker Street", "Circle", 4},
		{"Baker Street", "Bakerloo", "Baker Street", "Hammersmith & City", 4},
		{"Baker Street", "Bakerloo", "Baker Street", "Jubilee", 4},
		{"Baker Street", "Bakerloo", "Baker Street", "Metropolitan", 4},
		{"Charing Cross", "Bakerloo", "Charing Cross", "Northern", 3},
		{"Elephant & Castle", "Bakerloo", "Elephant & Castle", "Northern", 4},
		{"Embankment", "Bakerloo", "Embankment", "Circle", 4},
		{"Embankment", "Bakerloo", "Embankment", "District", 4},
		{"Embankment", "Bakerloo", "Embankment", "Northern", 4},
		{"Harrow & Wealdstone", "Bakerloo", "Harrow & Wealdstone", "Overground", 4},
		{"Kenton", "Bakerloo", "Kenton", "Overground", 4},
		{"Kenton", "Bakerloo", "Northwick Park", "Metropolitan", 8},
		{"Oxford Circus", "Bakerloo", "Oxford Circus", "Central", 3},
		{"Oxford Circus", "Bakerloo", "Oxford Circus", "Victoria", 3},
		{"Paddington", "Bakerloo", "Paddington", "Circle", 4},
		{"Paddington", "Bakerloo", "Paddington", "District", 4},
		{"Paddington", "Bakerloo", "Paddington", "Elizabeth", 6},
		{"Paddington", "Bakerloo", "Paddington", "Hammersmith & City", 4},
		{"Piccadilly Circus", "Bakerloo", "Piccadilly Circus", "Piccadilly", 3},
		{"Queen's Park", "Bakerloo", "Queen's Park", "Overground", 4},
		{"Waterloo", "Bakerloo", "Waterloo", "Jubilee", 4},
		{"Waterloo", "Bakerloo", "Waterloo", "Northern", 4},
		{"Waterloo", "Bakerloo", "Waterloo", "Waterloo & City", 4},
		{"Wembley Central", "Bakerloo", "Wembley Central", "Overground", 3},
		{"Willesden Junction", "Bakerloo", "Willesden Junction", "Overground", 4},

		// INTERCHANGES FROM CENTRAL LINE
		{"Bank", "Central", "Bank", "Docklands Light Railway", 6},
		{"Bank", "Central", "Bank", "Northern", 4},
		{"Bank", "Central", "Bank", "Waterloo & City", 4},
		{"Bank", "Central", "Monument", "Circle", 5},
		{"Bank", "Central", "Monument", "District", 5},
		{"Bond Street", "Central", "Bond Street", "Elizabeth", 5},
		{"Bond Street", "Central", "Bond Street", "Jubilee", 4},
		{"Ealing Broadway", "Central", "Ealing Broadway", "District", 4},
		{"Ealing Broadway", "Central", "Ealing Broadway", "Elizabeth", 5},
		{"Hanger Lane", "Central", "Park Royal", "Piccadilly", 11},
		{"Holborn", "Central", "Holborn", "Piccadilly", 4},
		{"Leytonstone", "Central", "Leytonstone High Road", "Overground", 14},
		{"Liverpool Street", "Central", "Liverpool Street", "Circle", 4},
		{"Liverpool Street", "Central", "Liverpool Street", "Elizabeth", 6},
		{"Liverpool Street", "Central", "Liverpool Street", "Hammersmith & City", 4},
		{"Liverpool Street", "Central", "Liverpool Street", "Metropolitan", 4},
		{"Mile End", "Central", "Mile End", "District", 4},
		{"Mile End", "Central", "Mile End", "Hammersmith & City", 4},
		{"Notting Hill Gate", "Central", "Notting Hill Gate", "Circle", 4},
		{"Notting Hill Gate", "Central", "Notting Hill Gate", "District", 4},
		{"Oxford Circus", "Central", "Oxford Circus", "Victoria", 4},
		{"Shepherd's Bush", "Central", "Shepherd's Bush", "Overground", 5},
		{"Stratford", "Central", "Stratford", "Docklands Light Railway", 5},
		{"Stratford", "Central", "Stratford", "Elizabeth", 5},
		{"Stratford", "Central", "Stratford", "Jubilee", 4},
		{"Stratford", "Central", "Stratford", "Overground", 6},
		{"Tottenham Court Road", "Central", "Tottenham Court Road", "Elizabeth", 5},
		{"Tottenham Court Road", "Central", "Tottenham Court Road", "Northern", 4},
		{"West Ruislip", "Central", "Ickenham", "Metropolitan", 15},
		{"West Ruislip", "Central", "Ickenham", "Piccadilly", 15},
		{"White City", "Central", "Wood Lane", "Circle", 4},
		{"White City", "Central", "Wood Lane", "Hammersmith & City", 4},

		// INTERCHANGES FROM CIRCLE LINE */
		{"Aldgate", "Circle", "Aldgate", "Metropolitan", 4},
		{"Aldgate", "Circle", "Tower Gateway", "Docklands Light Railway", 10},
		{"Baker Street", "Circle", "Baker Street", "Hammersmith & City", 3},
		{"Baker Street", "Circle", "Baker Street", "Jubilee", 4},
		{"Baker Street", "Circle", "Baker Street", "Metropolitan", 4},
		{"Barbican", "Circle", "Barbican", "Hammersmith & City", 3},
		{"Barbican", "Circle", "Barbican", "Metropolitan", 3},
		{"Barbican", "Circle", "Farringdon", "Elizabeth", 5},
		{"Blackfriars", "Circle", "Blackfriars", "District", 4},
		{"Cannon Street", "Circle", "Cannon Street", "District", 4},
		{"Edgware Road", "Circle", "Edgware Road", "District", 4},
		{"Edgware Road", "Circle", "Edgware Road", "Hammersmith & City", 3},
		{"Embankment", "Circle", "Embankment", "District", 4},
		{"Embankment", "Circle", "Embankment", "Northern", 4},
		{"Euston Square", "Circle", "Euston Square", "Hammersmith & City", 3},
		{"Euston Square", "Circle", "Euston Square", "Metropolitan", 3},
		{"Euston Square", "Circle", "Euston", "Northern", 6},
		{"Euston Square", "Circle", "Euston", "Overground", 7},
		{"Euston Square", "Circle", "Euston", "Victoria", 6},
		{"Euston Square", "Circle", "Warren Street", "Northern", 9},
		{"Euston Square", "Circle", "Warren Street", "Victoria", 9},
		{"Farringdon", "Circle", "Farringdon", "Elizabeth", 5},
		{"Farringdon", "Circle", "Farringdon", "Hammersmith & City", 3},
		{"Farringdon", "Circle", "Farringdon", "Metropolitan", 3},
		{"Gloucester Road", "Circle", "Gloucester Road", "District", 4},
		{"Gloucester Road", "Circle", "Gloucester Road", "Piccadilly", 4},
		{"Hammersmith", "Circle", "Hammersmith", "District", 4},
		{"Hammersmith", "Circle", "Hammersmith", "Hammersmith & City", 3},
		{"Hammersmith", "Circle", "Hammersmith", "Piccadilly", 4},
		{"King's Cross St. Pancras", "Circle", "King's Cross St. Pancras", "Hammersmith & City", 3},
		{"King's Cross St. Pancras", "Circle", "King's Cross St. Pancras", "Metropolitan", 3},
		{"King's Cross St. Pancras", "Circle", "King's Cross St. Pancras", "Northern", 4},
		{"King's Cross St. Pancras", "Circle", "King's Cross St. Pancras", "Piccadilly", 4},
		{"King's Cross St. Pancras", "Circle", "King's Cross St. Pancras", "Victoria", 4},
		{"Liverpool Street", "Circle", "Liverpool Street", "Elizabeth", 7},
		{"Liverpool Street", "Circle", "Liverpool Street", "Hammersmith & City", 4},
		{"Liverpool Street", "Circle", "Liverpool Street", "Metropolitan", 4},
		{"Monument", "Circle", "Bank", "Docklands Light Railway", 6},
		{"Monument", "Circle", "Bank", "Northern", 5},
		{"Monument", "Circle", "Bank", "Waterloo & City", 5},
		{"Monument", "Circle", "Monument", "District", 4},
		{"Moorgate", "Circle", "Liverpool Street", "Elizabeth", 10},
		{"Moorgate", "Circle", "Moorgate", "Hammersmith & City", 4},
		{"Moorgate", "Circle", "Moorgate", "Metropolitan", 4},
		{"Moorgate", "Circle", "Moorgate", "Northern", 4},
		{"Notting Hill Gate", "Circle", "Notting Hill Gate", "District", 4},
		{"Paddington", "Circle", "Paddington", "District", 4},
		{"Paddington", "Circle", "Paddington", "Elizabeth", 5},
		{"Paddington", "Circle", "Paddington", "Hammersmith & City", 3},
		{"South Kensington", "Circle", "South Kensington", "District", 4},
		{"South Kensington", "Circle", "South Kensington", "Piccadilly", 4},
		{"Tower Hill", "Circle", "Tower Gateway", "Docklands Light Railway", 5},
		{"Tower Hill", "Circle", "Tower Hill", "District", 4},
		{"Victoria", "Circle", "Victoria", "District", 4},
		{"Victoria", "Circle", "Victoria", "Victoria", 4},
		{"Westminster", "Circle", "Westminster", "District", 4},
		{"Westminster", "Circle", "Westminster", "Jubilee", 4},
		{"Wood Lane", "Circle", "Wood Lane", "Hammersmith & City", 3},

		// INTERCHANGES FROM DISTRICT LINE *
		{"Acton Town", "District", "Acton Town", "Piccadilly", 4},
		{"Aldgate East", "District", "Aldgate East", "Hammersmith & City", 4},
		{"Barking", "District", "Barking", "Hammersmith & City", 4},
		{"Barking", "District", "Barking", "Overground", 6},
		{"Bow Road", "District", "Bow Church", "Docklands Light Railway", 6},
		{"Bow Road", "District", "Bow Road", "Hammersmith & City", 4},
		{"Ealing Broadway", "District", "Ealing Broadway", "Elizabeth", 5},
		{"Ealing Common", "District", "Ealing Common", "Piccadilly", 4},
		{"Earl's Court", "District", "Earl's Court", "Piccadilly", 4},
		{"Embankment", "District", "Embankment", "Northern", 4},
		{"Gloucester Road", "District", "Gloucester Road", "Piccadilly", 4},
		{"Gunnersbury", "District", "Gunnersbury", "Overground", 5},
		{"Hammersmith", "District", "Hammersmith", "Hammersmith & City", 3},
		{"Hammersmith", "District", "Hammersmith", "Piccadilly", 4},
		{"Mile End", "District", "Mile End", "Hammersmith & City", 4},
		{"Monument", "District", "Bank", "Docklands Light Railway", 6},
		{"Monument", "District", "Bank", "Northern", 5},
		{"Monument", "District", "Bank", "Waterloo & City", 5},
		{"Paddington", "District", "Paddington", "Elizabeth", 5},
		{"Paddington", "District", "Paddington", "Hammersmith & City", 4},
		{"Richmond", "District", "Richmond", "Overground", 5},
		{"South Kensington", "District", "South Kensington", "Piccadilly", 4},
		{"Tower Hill", "District", "Tower Gateway", "Docklands Light Railway", 5},
		{"Upminster", "District", "Upminster", "Overground", 6},
		{"Victoria", "District", "Victoria", "Victoria", 4},
		{"West Brompton", "District", "West Brompton", "Overground", 5},
		{"West Ham", "District", "West Ham", "Docklands Light Railway", 5},
		{"West Ham", "District", "West Ham", "Hammersmith & City", 4},
		{"West Ham", "District", "West Ham", "Jubilee", 4},
		{"Westminster", "District", "Westminster", "Jubilee", 4},
		{"Whitechapel", "District", "Whitechapel", "Elizabeth", 5},
		{"Whitechapel", "District", "Whitechapel", "Hammersmith & City", 4},
		{"Whitechapel", "District", "Whitechapel", "Overground", 5},
		{"Wimbledon", "District", "Wimbledon", "Tramlink", 4},

		// INTERCHANGES FROM DOCKLANDS LIGHT RAILWAY LINE
		{"Bank", "Docklands Light Railway", "Bank", "Northern", 5},
		{"Bank", "Docklands Light Railway", "Bank", "Waterloo & City", 5},
		{"Bow Church", "Docklands Light Railway", "Bow Road", "Hammersmith & City", 6},
		{"Canary Wharf", "Docklands Light Railway", "Canary Wharf", "Elizabeth", 5},
		{"Canary Wharf", "Docklands Light Railway", "Canary Wharf", "Jubilee", 4},
		{"Canning Town", "Docklands Light Railway", "Canning Town", "Jubilee", 5},
		{"Custom House for ExCeL", "Docklands Light Railway", "Custom House for ExCeL", "Elizabeth", 6},
		{"Heron Quays", "Docklands Light Railway", "Canary Wharf", "Jubilee", 5},
		{"Poplar", "Docklands Light Railway", "Canary Wharf", "Elizabeth", 5},
		{"Shadwell", "Docklands Light Railway", "Shadwell", "Overground", 6},
		{"Stratford", "Docklands Light Railway", "Stratford", "Elizabeth", 5},
		{"Stratford", "Docklands Light Railway", "Stratford", "Jubilee", 4},
		{"Stratford", "Docklands Light Railway", "Stratford", "Overground", 5},
		{"Tower Gateway", "Docklands Light Railway", "Aldgate", "Metropolitan", 10},
		{"West Ham", "Docklands Light Railway", "West Ham", "Hammersmith & City", 4},
		{"West Ham", "Docklands Light Railway", "West Ham", "Jubilee", 4},
		{"West India Quay", "Docklands Light Railway", "Canary Wharf", "Elizabeth", 7},
		{"Woolwich Arsenal", "Docklands Light Railway", "Woolwich", "Elizabeth", 6},

		// INTERCHANGES FROM ELIZABETH LINE
		{"Bond Street", "Elizabeth", "Bond Street", "Jubilee", 5},
		{"Canary Wharf", "Elizabeth", "Canary Wharf", "Jubilee", 5},
		{"Farringdon", "Elizabeth", "Barbican", "Hammersmith & City", 5},
		{"Farringdon", "Elizabeth", "Barbican", "Metropolitan", 5},
		{"Farringdon", "Elizabeth", "Farringdon", "Hammersmith & City", 5},
		{"Farringdon", "Elizabeth", "Farringdon", "Metropolitan", 5},
		{"Forest Gate", "Elizabeth", "Wanstead Park", "Overground", 6},
		{"Heathrow Terminal 5", "Elizabeth", "Heathrow Terminals 2 & 3", "Piccadilly", 5},
		{"Liverpool Street", "Elizabeth", "Liverpool Street", "Hammersmith & City", 5},
		{"Liverpool Street", "Elizabeth", "Liverpool Street", "Metropolitan", 5},
		{"Liverpool Street", "Elizabeth", "Liverpool Street", "Overground", 6},
		{"Liverpool Street", "Elizabeth", "Moorgate", "Hammersmith & City", 6},
		{"Liverpool Street", "Elizabeth", "Moorgate", "Metropolitan", 6},
		{"Manor Park", "Elizabeth", "Woodgrange Park", "Overground", 10},
		{"Paddington", "Elizabeth", "Paddington", "Hammersmith & City", 5},
		{"Romford", "Elizabeth", "Romford", "Overground", 6},
		{"Stratford", "Elizabeth", "Stratford", "Jubilee", 4},
		{"Stratford", "Elizabeth", "Stratford", "Overground", 5},
		{"Tottenham Court Road", "Elizabeth", "Tottenham Court Road", "Northern", 5},
		{"Whitechapel", "Elizabeth", "Whitechapel", "Hammersmith & City", 5},
		{"Whitechapel", "Elizabeth", "Whitechapel", "Overground", 6},

		// INTERCHANGES FROM HAMMERSMITH & CITY LINE
		{"Baker Street", "Hammersmith & City", "Baker Street", "Jubilee", 4},
		{"Baker Street", "Hammersmith & City", "Baker Street", "Metropolitan", 4},
		{"Barbican", "Hammersmith & City", "Barbican", "Metropolitan", 3},
		{"Barking", "District", "Barking", "Overground", 6},
		{"Euston Square", "Hammersmith & City", "Euston Square", "Metropolitan", 3},
		{"Euston Square", "Hammersmith & City", "Euston", "Northern", 6},
		{"Euston Square", "Hammersmith & City", "Euston", "Overground", 7},
		{"Euston Square", "Hammersmith & City", "Euston", "Victoria", 6},
		{"Euston Square", "Hammersmith & City", "Warren Street", "Northern", 9},
		{"Euston Square", "Hammersmith & City", "Warren Street", "Victoria", 9},
		{"Farringdon", "Hammersmith & City", "Farringdon", "Metropolitan", 3},
		{"Hammersmith", "Hammersmith & City", "Hammersmith", "Piccadilly", 4},
		{"King's Cross St. Pancras", "Hammersmith & City", "King's Cross St. Pancras", "Metropolitan", 3},
		{"King's Cross St. Pancras", "Hammersmith & City", "King's Cross St. Pancras", "Northern", 4},
		{"King's Cross St. Pancras", "Hammersmith & City", "King's Cross St. Pancras", "Piccadilly", 4},
		{"King's Cross St. Pancras", "Hammersmith & City", "King's Cross St. Pancras", "Victoria", 4},
		{"Liverpool Street", "Hammersmith & City", "Liverpool Street", "Metropolitan", 4},
		{"Liverpool Street", "Hammersmith & City", "Liverpool Street", "Overground", 6},
		{"Moorgate", "Hammersmith & City", "Moorgate", "Metropolitan", 4},
		{"Moorgate", "Hammersmith & City", "Moorgate", "Northern", 4},
		{"West Ham", "Hammersmith & City", "West Ham", "Jubilee", 4},
		{"Whitechapel", "Hammersmith & City", "Whitechapel", "Overground", 5},

		// INTERCHANGES FROM JUBILEE LINE
		{"Baker Street", "Jubilee", "Baker Street", "Metropolitan", 4},
		{"Canada Water", "Jubilee", "Canada Water", "Overground", 6},
		{"Finchley Road", "Jubilee", "Finchley Road & Frognal", "Overground", 8},
		{"Finchley Road", "Jubilee", "Finchley Road", "Metropolitan", 5},
		{"Green Park", "Jubilee", "Green Park", "Piccadilly", 4},
		{"Green Park", "Jubilee", "Green Park", "Victoria", 4},
		{"Kilburn", "Jubilee", "Brondesbury", "Overground", 6},
		{"London Bridge", "Jubilee", "London Bridge", "Northern", 4},
		{"Stratford", "Jubilee", "Stratford", "Overground", 6},
		{"Waterloo", "Jubilee", "Waterloo", "Northern", 4},
		{"Waterloo", "Jubilee", "Waterloo", "Waterloo & City", 4},
		{"Wembley Park", "Jubilee", "Wembley Park", "Metropolitan", 4},
		{"West Hampstead", "Jubilee", "West Hampstead", "Overground", 5},

		// INTERCHANGES FROM METROPOLITAN LINE
		{"Euston Square", "Metropolitan", "Euston", "Northern", 6},
		{"Euston Square", "Metropolitan", "Euston", "Overground", 7},
		{"Euston Square", "Metropolitan", "Euston", "Victoria", 6},
		{"Euston Square", "Metropolitan", "Warren Street", "Northern", 9},
		{"Euston Square", "Metropolitan", "Warren Street", "Victoria", 9},
		{"Finchley Road", "Metropolitan", "Finchley Road & Frognal", "Overground", 8},
		{"Ickenham", "Metropolitan", "Ickenham", "Piccadilly", 4},
		{"King's Cross St. Pancras", "Metropolitan", "King's Cross St. Pancras", "Northern", 4},
		{"King's Cross St. Pancras", "Metropolitan", "King's Cross St. Pancras", "Piccadilly", 4},
		{"King's Cross St. Pancras", "Metropolitan", "King's Cross St. Pancras", "Victoria", 4},
		{"Liverpool Street", "Metropolitan", "Liverpool Street", "Overground", 6},
		{"Moorgate", "Metropolitan", "Moorgate", "Northern", 4},
		{"Northwick Park", "Metropolitan", "Kenton", "Overground", 8},
		{"Rayners Lane", "Metropolitan", "Rayners Lane", "Piccadilly", 4},

		// INTERCHANGES FROM NORTHERN LINE
		{"Archway", "Northern", "Upper Holloway", "Overground", 7},
		{"Camden Town", "Northern", "Camden Road", "Overground", 8},
		{"Clapham North", "Northern", "Clapham High Street", "Overground", 6},
		{"Euston", "Northern", "Euston", "Overground", 5},
		{"Euston", "Northern", "Euston", "Victoria", 4},
		{"Kentish Town", "Northern", "Kentish Town West", "Overground", 12},
		{"King's Cross St. Pancras", "Northern", "King's Cross St. Pancras", "Piccadilly", 4},
		{"King's Cross St. Pancras", "Northern", "King's Cross St. Pancras", "Victoria", 4},
		{"Leicester Square", "Northern", "Leicester Square", "Piccadilly", 4},
		{"Stockwell", "Northern", "Stockwell", "Victoria", 4},
		{"Warren Street", "Northern", "Warren Street", "Victoria", 4},
		{"Waterloo", "Northern", "Waterloo", "Waterloo & City", 4},

		// INTERCHANGES FROM OVERGROUND LINE
		{"Blackhorse Road", "Overground", "Blackhorse Road", "Victoria", 4},
		{"Dalston Junction", "Overground", "Dalston Kingsland", "Overground", 6},
		{"Euston", "Overground", "Euston", "Victoria", 5},
		{"Hackney Downs", "Overground", "Hackney Central", "Overground", 12},
		{"Highbury & Islington", "Overground", "Highbury & Islington", "Victoria", 5},
		{"New Cross Gate", "Overground", "New Cross", "Overground", 15},
		{"Seven Sisters", "Overground", "Seven Sisters", "Victoria", 5},
		{"South Tottenham", "Overground", "Seven Sisters", "Victoria", 9},
		{"Walthamstow Central", "Overground", "Walthamstow Central", "Victoria", 5},
		{"Walthamstow Queen's Road", "Overground", "Walthamstow Central", "Victoria", 8},
		{"West Croydon", "Overground", "West Croydon", "Tramlink", 6},

		// INTERCHANGES FROM PICCADILLY LINE
		{"Finsbury Park", "Piccadilly", "Finsbury Park", "Victoria", 4},
		{"Green Park", "Piccadilly", "Green Park", "Victoria", 4},
		{"King's Cross St. Pancras", "Piccadilly", "King's Cross St. Pancras", "Victoria", 4},
	}
}
